UPDATE itens_romaneio IR SET IR.codigo_produto = 1 WHERE IR.produto = 'Madeira 25x75';
UPDATE itens_romaneio IR SET IR.codigo_produto = 1 WHERE IR.produto = 'Madeira seca';
UPDATE itens_romaneio IR SET IR.codigo_produto = 2 WHERE IR.produto = 'Madeira limpa';
UPDATE itens_romaneio IR SET IR.codigo_produto = 3 WHERE IR.produto = 'Pinus bruto';
UPDATE itens_romaneio IR SET IR.codigo_produto = 4 WHERE IR.produto = 'Taboa bruta';
UPDATE itens_romaneio IR SET IR.codigo_produto = 4 WHERE IR.produto = 'Tabua bruta';
UPDATE itens_romaneio IR SET IR.codigo_produto = 5 WHERE IR.produto = 'Taboa de 30';
UPDATE itens_romaneio IR SET IR.codigo_produto = 5 WHERE IR.produto = 'Taboas de 30';
UPDATE itens_romaneio IR SET IR.codigo_produto = 6 WHERE IR.produto = 'Pranchas de pinus-Seca';
UPDATE itens_romaneio IR SET IR.codigo_produto = 7 WHERE IR.produto = 'Madeira bruta';
UPDATE itens_romaneio IR SET IR.codigo_produto = 7 WHERE IR.produto = 'Madeirab bruta';
UPDATE itens_romaneio IR SET IR.codigo_produto = 8 WHERE IR.produto = 'Madeira verde';
UPDATE itens_romaneio IR SET IR.codigo_produto = 9 WHERE IR.produto = 'Madeira para tratar(nossa)';
UPDATE itens_romaneio IR SET IR.codigo_produto = 10 WHERE IR.produto = 'Madeira para tratar';
UPDATE itens_romaneio IR SET IR.codigo_produto = 11 WHERE IR.produto = 'Madeira para secar';
UPDATE itens_romaneio IR SET IR.codigo_produto = 12 WHERE IR.produto = 'Madeira de 30';
UPDATE itens_romaneio IR SET IR.codigo_produto = 13 WHERE IR.produto = 'Madeira bruta limpa';
UPDATE itens_romaneio IR SET IR.codigo_produto = 13 WHERE IR.produto = 'Madeira Bruta-Limpa';
UPDATE itens_romaneio IR SET IR.codigo_produto = 14 WHERE IR.produto = 'Madeira bruta verde';
UPDATE itens_romaneio IR SET IR.codigo_produto = 15 WHERE IR.produto = 'Madeira bruta seca';
UPDATE itens_romaneio IR SET IR.codigo_produto = 16 WHERE IR.produto = 'Eucalipto bruto';
UPDATE itens_romaneio IR SET IR.codigo_produto = 17 WHERE IR.produto = 'Estoque madeira verde';
UPDATE itens_romaneio IR SET IR.codigo_produto = 18 WHERE IR.produto = 'Chassi-reto';
UPDATE itens_romaneio IR SET IR.codigo_produto = 19 WHERE IR.produto = 'Chassi-Painel';
UPDATE itens_romaneio IR SET IR.codigo_produto = 20 WHERE IR.produto = 'Chassi-lousa 2';
UPDATE itens_romaneio IR SET IR.codigo_produto = 21 WHERE IR.produto = 'Chassi-DU';
UPDATE itens_romaneio IR SET IR.codigo_produto = 22 WHERE IR.produto = 'Chassi-CH';
UPDATE itens_romaneio IR SET IR.codigo_produto = 23 WHERE IR.produto = 'Chassi';
UPDATE itens_romaneio IR SET IR.codigo_produto = 24 WHERE IR.produto = 'Assoalho';